# Generated by Django 5.0.4 on 2024-04-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='is_there',
            field=models.BooleanField(default=True),
        ),
    ]
