# Generated by Django 5.0.4 on 2024-04-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Waitress', 'Waitress'), ('Courier', 'Courier'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
