# Generated by Django 5.0.4 on 2024-04-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_order_items_order_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
